name: CI for Go Code #Naming the workflow
on: #for event triggering
  push:
    branches: [main] #add with coma for more branches to monitor
  pull_request:
    branches: [main]
    
jobs: # job to execute?
  build: # name of the job
    name: Load OS #name for printing
    runs-on: ubuntu-latest #specify os in virtual machine
    steps:
    - name: Print Hello
      run: | #run terminal command
        ls
        echo Hello!
